### PR TITLE
Return inverse of the pose

### PR DESCRIPTION
**Pull request by vsuryamurthy**
@de-vri-es The reason I asked for your review is because I would assume both cases to work but it doesnt.
pose->inverse() vs pose = pose->inverse()

### CODE REVIEW

**Review by vcarpani — APPROVED** [review]

**Comment by vcarpani** [comment]
@vsuryamurthy `inverse` is a `const` function, so it cannot change pose:
https://eigen.tuxfamily.org/dox/classEigen_1_1MatrixBase.html#a7712eb69e8ea3c8f7b8da1c44dbdeebf

**Comment by de-vri-es** [comment]
Good catch, but one big but: how will this impact existing systems? This is a backwards incompatible change that doesn't break compilation. Those are scary.

Also, this is even customer facing through the calibration server, isn't it?

**Comment by vsuryamurthy** [comment]
@de-vri-es This was the case earlier before Haluk refactored it and it kinda slipped through my eyes. Earlier it used be in one statement like below,
``` 
Eigen::Isometry3d pose = toEigenIsometry(stereo_node[itmLink]).inverse();

**Comment by de-vri-es** [comment]
Ah, so it's broken now. Are any customers currently affected?

**Review by de-vri-es — APPROVED** [review]

**Pull request merged**
